package cn.xiahou.entity;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "jd_item")
public class JdItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.id
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    //自增主键
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.spu
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private Long spu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.sku
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private Long sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.title
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.price
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.url
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.createtime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.updatetime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD_ITEM.pic
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.id
     *
     * @return the value of JD_ITEM.id
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.id
     *
     * @param id the value for JD_ITEM.id
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getSpu() {
        return spu;
    }

    public void setSpu(Long spu) {
        this.spu = spu;
    }

    public Long getSku() {
        return sku;
    }

    public void setSku(Long sku) {
        this.sku = sku;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.title
     *
     * @return the value of JD_ITEM.title
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.title
     *
     * @param title the value for JD_ITEM.title
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.price
     *
     * @return the value of JD_ITEM.price
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.price
     *
     * @param price the value for JD_ITEM.price
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.url
     *
     * @return the value of JD_ITEM.url
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.url
     *
     * @param url the value for JD_ITEM.url
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.createtime
     *
     * @return the value of JD_ITEM.createtime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.createtime
     *
     * @param createtime the value for JD_ITEM.createtime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD_ITEM.updatetime
     *
     * @return the value of JD_ITEM.updatetime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD_ITEM.updatetime
     *
     * @param updatetime the value for JD_ITEM.updatetime
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }
}