package cn.xiahou.entity;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.ID
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.NAME
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.ID
     *
     * @return the value of TEST.ID
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.ID
     *
     * @param id the value for TEST.ID
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.NAME
     *
     * @return the value of TEST.NAME
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.NAME
     *
     * @param name the value for TEST.NAME
     *
     * @mbg.generated Fri Feb 14 10:53:39 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}